### ISSUE TITLE
Videos stop playing after about one minute

### ISSUE THREAD

**Issue by markd15** [pixeltailgames/cinema#102] opened 2015-08-24 06:21 UTC
I've been playing with the Cinema Gamemode for quite some time now. Just recently (within the past few months really) I have encountered a strange bug which I can't find any information on.

When a video begins playing it will work normally until about the one minute mark where it will freeze. The game at this point is still playable. All of the functions of the cinema still work, and the time at the bottom of the frozen video will continue to count foreword. At the end of the videos time the next video will begin playing for about one minute before freezing again. The frozen video does not play sound or video. Refreshing the theater will allow the video to continue playing for about another minute before freezing again.

This used to happen (videos freezing, although not always at one minute in) every once and a while but a theater refresh would fix it. Now the bug is permanent and happens every time I play Cinema.

I found this bug on Windows 8.1 and updating to Windows 10 did not change anything. I have checked and updated Flash, computer drivers, and all game assets. I have reinstalled the game. Nothing I have tried has fixed this bug even temporarily. As far as I remember I did not change anything before this issue appeared.

I have asked many people on different servers about this and no one seems to have a solution. Google is also of little help. I am hoping someone here can help. I look foreword to hearing back from your responses.Thank you

**Comment by samuelmaddock** [comment] 2015-08-24 06:34
Which type of video are you watching when experiencing this issue, YouTube? Do you have a link to a video this issue occurs on? I'm aware you said it happens every time, but it would be great if I was able to reproduce this.

**Comment by markd15** [comment] 2015-08-24 06:55
It happens with YouTube for sure. I'm not sure about other sites. Honestly it's hard to think of a specific video because it happens to all of them. You could try Young and Beautiful by Lana Del Rey. That's one I know it happens on.

I should add that it doesn't matter if I request the video or if I'm just watching a video put up by someone else. Also it doesn't matter if it's the beginning of the video, or I'm jumping into the middle of one.

Thanks for the quick response too.

**Comment by markd15** [comment] 2015-09-15 05:13
Have you been able to look into this issue?

**Comment by WinterPhoenix96** [comment] 2015-09-15 23:29
A question. Does the "Time Elapsed" bar on the bottom of the Theater Screen when you hold Q stop as well, or just the video itself?

**Comment by WinterPhoenix96** [comment] 2015-09-15 23:38
Also one of the problem videos was this one, correct? http://www.youtube.com/watch?v=o_1aF54DO60

**Comment by markd15** [comment] 2015-09-16 19:39
Just the video/audio stops. The "Time Elapsed" bar will continue counting and if the theater is refreshed the video will start playing again not from where it stopped, but from where the video is for everyone else. In other words the videos remain synced with the servers time even after it has frozen for me which allows me to refresh and continue watching alongside everyone else. The problem of course is that I've now missed several seconds of the video.

Yes that video stops as described in my first post, although I'll say again that the problem exists for all videos I've tested. It also exists for videos others put up.

I'll also add the I have disabled cloud sync, deleted local content, and deleted the Gmod folder then reinstalled. This allowed me to try again with a clean install of Gmod, but the problem persists.

**Comment by WinterPhoenix96** [comment] 2015-09-16 19:43
This seems like an extremely rare issue, perhaps with some combination of the configuration or things in your setup, or your setup itself. Could you post your computer's specifications by chance?

**Comment by markd15** [comment] 2015-09-16 20:15
Processor: AMD A10-5800K APU (3.8 GHz base)(4.2 GHz max)
RAM: 8 GB (7.2 GB for CPU)(0.8 GB for GPU) G.SKILL Ripjaws F3-17000CL11D-8GBXL
OS: Windows 10 64-bit
Motherboard: MSI FM2-A75MA-E35

None of these items (excluding OS) have been changed since the computer was built. The issue appeared before the upgrade to Windows 10.

**Comment by WinterPhoenix96** [comment] 2015-09-16 22:31
Was there ever a time when you didn't have this issue, and if so, what was your OS at the time?

**Comment by markd15** [comment] 2015-09-16 22:36
Yes for several months I never had this problem. My OS was always Windows 8.1 until the Windows 10 update a little over a month ago. The issue showed up a couple months before the Windows 10 update.

**Comment by Herover** [comment] 2015-09-16 22:49
While I'm not 100% sure if youtube in Cinema use Flash or HTML5, do you know what version of flash your garrys mod is using? You can check it by starting a local server with Cinema and load the URL https://www.adobe.com/software/flash/about/ into the browser (may need `cinema_allow_url 1`),
It should be 18,0,0,232 (take note at the little gray box left of the text).

**Comment by markd15** [comment] 2015-09-16 22:52
You're going to have to be a 'little' more specific about how to check my Flash version. I don't have much (read: any) practice with local servers.

**Comment by WinterPhoenix96** [comment] 2015-09-16 22:53
Well, any Cinema server would work actually for just that.

Also Cinema unfortunately can only use Flash-based players, as HTML5 video support is not complete in Awesomium, the Web Browser Implementation used for Garry's Mod. See more info on that here: https://github.com/Facepunch/garrysmod-requests/issues/531

**Comment by Herover** [comment] 2015-09-16 22:55
* Subscribe to these workshop items
* Open Garry's Mod and fine the button "Start New Game"
* Choose a Cinema map, and choose the Cinema gamemode at bottom right of the screen
* Start Game

Or, as WinderPhoenix96 said any server would actually work for that :)

Or just prematurely reinstall Flash from https://get3.adobe.com/flashplayer/update/plugin/ even if you already got it.

**Comment by WinterPhoenix96** [comment] 2015-09-16 22:57
He actually needs to use the Other Versions Link for that, as he needs to get the NPAPI version specifically, instead of whatever his current web browser uses: https://get.adobe.com/flashplayer/otherversions/

**Comment by markd15** [comment] 2015-09-16 22:59
I have NPAPI Version 18.0.0.232
I do not have a PPAPI Version installed

**Comment by WinterPhoenix96** [comment] 2015-09-16 23:04
NPAPI is what Awesomium uses and that's the latest... *sigh* All I can think of is something in your configuration changed at some point to make it less than reliable. I would try reinstalling Flash Player from scratch, using Programs and Features in the Start Menu/Control Panel, and see if that works.

**Comment by markd15** [comment] 2015-09-16 23:10
I'll do that. Also I just checked in game and while the steam overlay browser cant find the flash plugin for some reason, the video browser identifies the newest version as being installed.

I tried playing a video in what I guess is a "local server" (just single player in the default cinema map and game mode) and it started buffering at 30 seconds in which is slightly odd. It wouldn't finish buffering so i refreshed the theater with HD video turned off and it continued at about 40 seconds in. at 1:35 it froze. This is clearly the original problem at work.

**Comment by WinterPhoenix96** [comment] 2015-09-16 23:14
The Steam Overlay Browser is a totally different Web Browser that's integrated with Steam called ISteamHTMLSurface. Garry's Mod uses Awesomium.

**Comment by markd15** [comment] 2015-09-16 23:20
Just reinstalled Flash and tried again. The first video I tested froze at 55. The second froze at 1:10. Flash doesn't seem to be the problem.

**Comment by WinterPhoenix96** [comment] 2015-09-16 23:22
Did you reboot after reinstalling Flash?

**Comment by markd15** [comment] 2015-09-16 23:23
Well... Excuse me for a moment...

**Comment by markd15** [comment] 2015-09-16 23:36
Huh.. So the cinema game mode and all of my addons just vanished after a restart. Something strange is going on.

**Comment by WinterPhoenix96** [comment] 2015-09-16 23:37
That's new...

**Comment by markd15** [comment] 2015-09-16 23:47
Another restart and everything is back. Flash is installed and yet the video I tested froze at the exact same 55 second mark as before.

**Comment by WinterPhoenix96** [comment] 2015-09-16 23:56
Something funky is definitely going on... I honestly just don't know at this point. Maybe networking related? I dunno.

**Comment by markd15** [comment] 2015-09-16 23:59
All of my addons are gone again. I ran a disk cleaner and checked my hard drive's surface (which showed nothing of course) and now my addon list is empty. Do addons require an internet connection to show up?

**Comment by WinterPhoenix96** [comment] 2015-09-17 00:00
I think they do?

**Comment by markd15** [comment] 2015-09-17 00:00
And now everything is back! This is confusing.

**Comment by WinterPhoenix96** [comment] 2015-09-17 00:04
Indeed it is.

**Comment by markd15** [comment] 2015-09-17 00:05
I fixed it... Let me just check something but I think I know what happened.

**Comment by WinterPhoenix96** [comment] 2015-09-17 00:14
Alright.

**Comment by markd15** [comment] 2015-09-17 00:23
(OP vanishes, never to be heard from again.)

Kidding.

Yep for sure it was a connection issue but not the sort that you might expect. I was using PDA Net and my smartphone as my internet connection. Verizon 4G beats my computers DSL connection even on a bad day so I use PDA Net to share that connection with my computer.

Now nothing has changed with that connection as far as I'm aware but turning off PDA Net and switching to DSL (Ethernet) fixes the video stopping problem (although videos take longer to start now..).

Also the missing addons problem was because I was starting Gmod before my internet connection had been established and it couldn't lookup my addon list.

So the question now is why does PDA Net cause this problem when DSL (Ethernet) doesn't?

**Comment by WinterPhoenix96** [comment] 2015-09-17 00:53
Potential issues with MTU or MSS, perhaps.

**Comment by markd15** [comment] 2015-09-17 22:35
Is there any way to fix something like that? It wasn't always like this. It just stopped working one day (there was probably some update or something but i don't remember).

**Comment by WinterPhoenix96** [comment] 2015-09-18 00:44
There's...ways, yes, however they're rather complicated and involve messing around with your network configuration. I think the best you can do would be to try reinstalling PDANet, honestly.

**Comment by markd15** [comment] 2015-09-18 00:48
Oh well I reinstalled PDA Net just recently.

**Comment by samuelmaddock** [comment] 2015-09-18 02:22
I'm going to close this since it seems to be a problem with your internet connection rather than Cinema. Feel free to continue discussion though, I'll reopen if needed.

**Closed by samuelmaddock** 2015-09-18 02:22 UTC
Labels: invalid
